import os
import subprocess
from zipfile import ZipFile

def create_wrapper(project_path, framework):
    build_dir = os.path.join(project_path, "build")
    os.makedirs(build_dir, exist_ok=True)

    if framework == "Django":
        entry_script = "manage.py"
    elif framework == "Flask" or framework == "Streamlit":
        entry_script = "app.py"
    else:
        raise ValueError("Unsupported framework")

    entry_path = None
    for root, _, files in os.walk(project_path):
        if entry_script in files:
            entry_path = os.path.join(root, entry_script)
            break

    if entry_path is None:
        raise FileNotFoundError(f"{entry_script} not found.")

    # Generate launcher script
    launcher_script = os.path.join(build_dir, "launcher.py")
    with open(launcher_script, "w") as f:
        f.write(f"import os\nos.system('python {entry_path}')")

    # Run PyInstaller
    subprocess.run(["pyinstaller", "--onefile", launcher_script], cwd=build_dir)

    # Zip only if EXE was built
    dist_path = os.path.join(build_dir, "dist")
    exe_files = [f for f in os.listdir(dist_path) if f.endswith(".exe")]

    if not exe_files:
        raise RuntimeError("No .exe file generated by PyInstaller")

    output_zip = os.path.join(project_path, "chatbot_desktop.zip")
    with ZipFile(output_zip, "w") as zipf:
        for file in exe_files:
            zipf.write(os.path.join(dist_path, file), arcname=file)

    return output_zip
